[package]
name = "calib-targets-chessboard"
version = "0.1.0"
edition = "2021"
description = "Plain chessboard detector built on top of ChESS corners"
license = "MIT OR Apache-2.0"

[features]
tracing = ["calib-targets-core/tracing", "dep:tracing", "dep:tracing-log",
    "dep:tracing-subscriber"]

[dependencies]
calib-targets-core = { path = "../calib-targets-core", version = "0.1" }
nalgebra = "0.34"
log = "0.4"
kiddo = "5.2.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
tracing = { version = "0.1", optional=true }
tracing-log = { version = "0.2", optional = true }
tracing-subscriber = { version = "0.3", optional = true, features = ["fmt", "env-filter"] }

[dev-dependencies]
image = { version = "0.25", default-features = true }
chess-corners = { version = "0.2" }
