[package]
name = "calib-targets-rs"
version = "0.1.0"
edition = "2021"
publish = false

[workspace]
members = [
    "calib-targets-core",
    "calib-targets-chessboard",
    "calib-targets-charuco",
    "calib-targets-aruco",
    "calib-targets-marker",
]

resolver = "2"

[dependencies]
calib-targets-core = { path = "calib-targets-core" }
calib-targets-chessboard = { path = "calib-targets-chessboard" }
calib-targets-charuco = { path = "calib-targets-charuco" }
calib-targets-aruco = { path = "calib-targets-aruco" }
chess-corners = "0.1"
image = { version = "0.25", default-features = true }
nalgebra = "0.34"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
log = "0.4"
tracing = "0.1"
tracing-subscriber = "0.3"
tracing-log = "0.2"
