[package]
name = "calib-targets-marker"
version = "0.1.0"
edition = "2021"
description = "Checkerboard marker target detector (checkerboard + 3 central circles)"
license = "MIT OR Apache-2.0"

[dependencies]
calib-targets-core = { path = "../calib-targets-core" }
calib-targets-chessboard = { path = "../calib-targets-chessboard" }
nalgebra = "0.34"
