[package]
name = "calib-targets-charuco"
version = "0.1.2"
description = "ChArUco board detector built on top of calib-targets-core"
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
rust-version.workspace = true
readme = "README.md"
documentation.workspace = true
keywords = ["calibration", "computer-vision", "charuco", "aruco", "chessboard"]
categories = ["computer-vision", "science"]

[features]
tracing = ["calib-targets-core/tracing", "dep:tracing"]

[dependencies]
calib-targets-core = { path = "../calib-targets-core", version = "0.1" }
calib-targets-chessboard = { path = "../calib-targets-chessboard", version = "0.1" }
calib-targets-aruco = { path = "../calib-targets-aruco", version = "0.1" }
nalgebra = "0.34"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
tracing = { version = "0.1", optional=true }
log = "0.4"

[dev-dependencies]
chess-corners = { version = "0.2", features = ["rayon"] }
image = { version = "0.25", default-features = true }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
