[package]
name = "calib-targets-charuco"
version = "0.1.0"
edition = "2021"
description = "ChArUco board detector built on top of calib-targets-core"
license = "MIT"

[features]
tracing = ["dep:tracing"]

[dependencies]
calib-targets-core = { path = "../calib-targets-core", version = "0.1" }
calib-targets-chessboard = { path = "../calib-targets-chessboard", version = "0.1" }
calib-targets-aruco = { path = "../calib-targets-aruco", version = "0.1" }
nalgebra = "0.34"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
tracing = { version = "0.1", optional=true }
log = "0.4"

[dev-dependencies]
chess-corners = "0.2"
image = { version = "0.25", default-features = true }
