[package]
name = "calib-targets"
version = "0.1.0"
edition = "2021"
description = "Main entry point crate for a collection of plain calibration target detectors built on top of ChESS corners"
license = "MIT OR Apache-2.0"

[features]
default = []
tracing = ["dep:tracing", "dep:tracing-log", "dep:tracing-subscriber"]

[dependencies]
calib-targets-charuco = { path = "../calib-targets-charuco", version = "0.1" }
calib-targets-aruco = { path = "../calib-targets-aruco", version = "0.1" }
calib-targets-core = { path = "../calib-targets-core", version = "0.1" }
calib-targets-chessboard = { path = "../calib-targets-chessboard", version = "0.1" }
chess-corners = { version = "0.1" }
nalgebra = "0.34"
log = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
image = { version = "0.25", default-features = true }
tracing = { version = "0.1", optional = true }
tracing-log = { version = "0.2", optional = true }
tracing-subscriber = { version = "0.3", optional = true, features = ["fmt", "env-filter"] }
